---
#### SECRET DO AMBIENTE DE PRODUCTION
apiVersion: v1
kind: Secret
metadata:
  name: questcode-backend-user
  namespace: prod
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9xdWVzdGNvZGU6ZjZZRlB6TElJd0NRWWc1eUBjbHVzdGVyMC15c2Z5bS5tb25nb2RiLm5ldC90ZXN0Cg=="
  SECRET_OR_KEY: "YjAwdEM0bXAxOAo="
  GITHUB_CLIENT_SECRET: "ZDJlNDY1MTRkODk1MWNlN2FjNDM4ZDM1MGFhZGVlNWY3MmE0YjBmMAo="

---
#### SECRET DO AMBIENTE DE STAGING
apiVersion: v1
kind: Secret
metadata:
  name: questcode-backend-user
  namespace: staging
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9xdWVzdGNvZGU6ZjZZRlB6TElJd0NRWWc1eUBjbHVzdGVyMC15c2Z5bS5tb25nb2RiLm5ldC90ZXN0Cg=="
  SECRET_OR_KEY: "YjAwdEM0bXAxOAo="
  GITHUB_CLIENT_SECRET: "ZDJlNDY1MTRkODk1MWNlN2FjNDM4ZDM1MGFhZGVlNWY3MmE0YjBmMAo="
  